/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package peluqueriaCanina.logica;

import peluqueriaCanina.gui.Principal;

public class App {
    public static void main (String[] args){
        Principal ventanaPrincipal = new Principal();
        ventanaPrincipal.setVisible(true);
        ventanaPrincipal.setLocationRelativeTo(null);
    }
}
